apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test2-poi-map-app-dev
  annotations:
    argocd/app-name: test2-poi-map-app-dev
    backstage.io/kubernetes-id: test2-poi-map-app
    backstage.io/kubernetes-namespace: test2
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-xchange/test2-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa-cvtl6.9nln.p1.openshiftapps.com/dev-pipelines/ns/test2/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa-cvtl6.9nln.p1.openshiftapps.com/k8s/ns/test2/deployments/test2-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa-cvtl6.9nln.p1.openshiftapps.com/#https://github.com/rhdh-xchange/test2-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://test2-poi-map-app-test2.apps.rosa-cvtl6.9nln.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/ryanj"
  system: workshop-system-test2
  consumesApis:
    - gateway-api-test2
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-test2
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/ryanj"
